version: '3'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password


  php_server:
    build: docker/php-server
    volumes:
      - ./:/srv/app
